- include: stop_hdfs.yml
- include: remove_data.yml
- include: format_hdfs.yml
- include: start_hdfs.yml
- include: create_tmp_dir.yml
- include: create_user_dir.yml
- include: init_spark.yml
#- include: init_hbase.yml
